<a href="https://colab.research.google.com/github/Saisneha0209/Machine-Learning/blob/main/Deep_Learning_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow as tf
import matplotlib as mlt
import numpy as np
from tensorflow import keras
#SPLITTING TESTING AND TRAINING DATASETS!!
#Data to be taken by MNIST and dataset formed under YannLeCunn!!
#Image knowns three colours RGB!!
#Images(0-255 Bits)!!
#x_train=x_train/255,from this we will get in binary computation form!!!
#x_test=x_test=/255,y_train and y_test no need cause we were doing for the images formation!!!
(x_train,y_train),(x_test,y_test)=keras.datasets.mnist.load_data()
print(x_train)
print("--------------------------------------------")
print(y_train)#info of numbers in list like the pixels and then it compresses it!
#to make the model keras has flatten and dense!!
#Flaten is a function and works in input layer!!
#Dense function takes the hidden layer and output!!
#optimiser and activation fucntion for dense!!
#1.input layer,2.hidden layer ,3.output layer...
#flattennn then dense and then dense to be used in this...
#TAKING IMAGES 28 BY 28...
#how much hidden layer needed to be done put that value according to complexity...
#(128,activation=relu)
#in dense there is output layer and softmax needed soo in output layer alsoo you have to give the numbers of layers you want to use ...
#input layer we have flatten ; sameeee syntax .....
models=keras.sequential(1.)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
--------------------------------------------
[5 0 4 ... 5 6 8]
