<a href="https://colab.research.google.com/github/Saisneha0209/Machine-Learning/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install tensorflow

In [ ]:
import tensorflow as tf
a=tf.constant(5)  #0 Dimension!!   #yahan constant matlab numpy mai array!!and in that np.array but here tf.constant!!
print(a)
b=tf.constant([45,56])
print(b)  #1 Dimension!!
c=tf.constant([[4,5,1],[4,6,7]])  #2 Dimension
print(c)
#On 4-D IT IS TENSOR!!!
#SAME VECTOR KO ADD,MULTIPLY KARNA!!!!

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([45 56], shape=(2,), dtype=int32)
tf.Tensor(
[[4 5 1]
 [4 6 7]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a+b)

tf.Tensor([50], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a*b)

tf.Tensor([225], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a/b)

tf.Tensor([0.11111111], shape=(1,), dtype=float64)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a//b)

tf.Tensor([0], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a-b)

tf.Tensor([-40], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5,6,7])
b=tf.constant([1,2,3,4])
#print(a+b) THIS WILL GIVE ERROR BECAUSE YOU HAVE LEARNT IN MATRICES THAT ROW * COLOUMNS MUST BE EQUAL TO MEANS THE
#COLOUMNS SHOULD BE EQUAL TO ROW OF SECOND MATRICES .....

In [ ]:
import tensorflow as tf
w = tf.constant([[5,4,3],
                 [2,2,3],
                 [1,2,6],
                 [2,1,2]])
x = tf.constant([[3],
                 [2],
                 [1]])
b = tf.constant([[1],
                 [5],
                 [6],
                 [0]])

y = tf.matmul(w, x) + b

print(y)
#broadcasting laws in this and do it like 3-D!!!!!

tf.Tensor(
[[27]
 [18]
 [19]
 [10]], shape=(4, 1), dtype=int32)


In [ ]:
#zero tf and once tf!!!!

In [ ]:
import tensorflow as tf

w = tf.constant([5, 3, 2])
x = tf.constant([3,
                 1,
                 5])
b = tf.constant([[2]])   # make bias 2D as well
w = tf.reshape(w, (1, 3))
x = tf.reshape(x, (3, 1))
y = tf.matmul(w, x) + b
#without matmal what you can do is simply doo by MATRICES method!!!!
print(y)

tf.Tensor([[30]], shape=(1, 1), dtype=int32)


In [ ]:
a = tf.constant([54, 37, 2],dtype =tf.float32)  #yeh kyun karte hai cause saare no are in float during doing neural network!!!!
print(a)

tf.Tensor([54. 37.  2.], shape=(3,), dtype=float32)


In [ ]:
a = tf.constant([5, 3, 2])
b = w = tf.constant([4,7,8])
add=tf.add(a,b)
print(add)  #BUILT-IN FUNCTION!!!

tf.Tensor([ 9 10 10], shape=(3,), dtype=int32)


In [ ]:
#a=[1,2,3]
#reduction function to calculate loss function error find
#tf.reduce_sum of a!!!!!
a = tf.constant([5, 3, 2])
print(tf.reduce_sum(a))
# and now to find out the mean!!!
print(tf.reduce_mean(a))   #tensor ke elements ko add karna!!!!#during list and numpy we have done it!!!

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
#Numpy is CPU friendly and deep learning things are GPU ke dost!!!

In [9]:
import tensorflow as tf
a = tf.constant([0.33,0.66,0.34])
print(tf.random.uniform([3]))  #Generates randomly within this range!!!!

tf.Tensor([0.60458374 0.7468035  0.35423875], shape=(3,), dtype=float32)


In [12]:
import tensorflow as tf
a = tf.constant([0.33,0.66,0.34])
print(tf.random.uniform([100],minval = 5 , maxval = 12))

tf.Tensor(
[11.484494   5.9807477 11.968439  10.190077  11.764732   5.7636776
 11.182028   8.857251  11.405127   6.622029  11.257896  11.384124
  8.676034   7.3900247 11.134888   9.960755   5.248499  11.547871
  6.5740213  7.3855276  6.707655   5.6653266  6.3710318 10.407521
  8.527727   7.204861   9.569986   5.9534044  9.07359    5.0174093
  8.492466   9.692235  11.9751625 10.644306  11.022914  10.833286
  9.949727   7.884965   7.3325567  6.277651   8.462965   9.096923
 10.718992   9.530847  10.1920595  7.515457   6.5758686  5.3364854
 10.971554  11.528613   5.850489   5.174097  11.133522   6.518083
  5.0614223  7.8816233 10.391401   9.860551   8.544971   8.479079
  8.031696   7.3067703  9.360556   7.203604  10.075134   8.998576
 10.773348   5.666126   9.352852   5.1073666 11.051652  10.428591
 10.185446   7.3736506  8.7911215  8.8528385 10.870892   8.482973
  8.517784   5.64455    9.20896    7.952837   5.372307  10.300545
  6.7689147  6.853962   6.1305532  8.43971    5.0698767 10.104