<a href="https://colab.research.google.com/github/Saisneha0209/Machine-Learning/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install tensorflow

In [ ]:
import tensorflow as tf
a=tf.constant(5)  #0 Dimension!!   #yahan constant matlab numpy mai array!!and in that np.array but here tf.constant!!
print(a)
b=tf.constant([45,56])
print(b)  #1 Dimension!!
c=tf.constant([[4,5,1],[4,6,7]])  #2 Dimension
print(c)
#On 4-D IT IS TENSOR!!!
#SAME VECTOR KO ADD,MULTIPLY KARNA!!!!

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([45 56], shape=(2,), dtype=int32)
tf.Tensor(
[[4 5 1]
 [4 6 7]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a+b)

tf.Tensor([50], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a*b)

tf.Tensor([225], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a/b)

tf.Tensor([0.11111111], shape=(1,), dtype=float64)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a//b)

tf.Tensor([0], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a-b)

tf.Tensor([-40], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5,6,7])
b=tf.constant([1,2,3,4])
#print(a+b) THIS WILL GIVE ERROR BECAUSE YOU HAVE LEARNT IN MATRICES THAT ROW * COLOUMNS MUST BE EQUAL TO MEANS THE
#COLOUMNS SHOULD BE EQUAL TO ROW OF SECOND MATRICES .....

In [11]:
import tensorflow as tf
w = tf.constant([[5,4,3],
                 [2,2,3],
                 [1,2,6],
                 [2,1,2]])
x = tf.constant([[3],
                 [2],
                 [1]])
b = tf.constant([[1],
                 [5],
                 [6],
                 [0]])

y = tf.matmul(w, x) + b

print(y)
#broadcasting laws in this and do it like 3-D!!!!!

tf.Tensor(
[[27]
 [18]
 [19]
 [10]], shape=(4, 1), dtype=int32)
