<a href="https://colab.research.google.com/github/Saisneha0209/Machine-Learning/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install tensorflow

#TENSORFLOW!!

In [ ]:
import tensorflow as tf
a=tf.constant(5)  #0 Dimension!!   #yahan constant matlab numpy mai array!!and in that np.array but here tf.constant!!
print(a)
b=tf.constant([45,56])
print(b)  #1 Dimension!!
c=tf.constant([[4,5,1],[4,6,7]])  #2 Dimension
print(c)
#On 4-D IT IS TENSOR!!!
#SAME VECTOR KO ADD,MULTIPLY KARNA!!!!

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([45 56], shape=(2,), dtype=int32)
tf.Tensor(
[[4 5 1]
 [4 6 7]], shape=(2, 3), dtype=int32)


#ALL ARITHMETIC OPERATIONS!!

In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a+b)

tf.Tensor([50], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a*b)

tf.Tensor([225], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a/b)

tf.Tensor([0.11111111], shape=(1,), dtype=float64)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a//b)

tf.Tensor([0], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a-b)

tf.Tensor([-40], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5,6,7])
b=tf.constant([1,2,3,4])
#print(a+b) THIS WILL GIVE ERROR BECAUSE YOU HAVE LEARNT IN MATRICES THAT ROW * COLOUMNS MUST BE EQUAL TO MEANS THE
#COLOUMNS SHOULD BE EQUAL TO ROW OF SECOND MATRICES .....

#Y = W * X + B

In [ ]:
import tensorflow as tf
w = tf.constant([[5,4,3],
                 [2,2,3],
                 [1,2,6],
                 [2,1,2]])
x = tf.constant([[3],
                 [2],
                 [1]])
b = tf.constant([[1],
                 [5],
                 [6],
                 [0]])

y = tf.matmul(w, x) + b

print(y)
#broadcasting laws in this and do it like 3-D!!!!!

tf.Tensor(
[[27]
 [18]
 [19]
 [10]], shape=(4, 1), dtype=int32)


In [ ]:
#zero tf and once tf!!!!   (matrices)

In [ ]:
import tensorflow as tf

w = tf.constant([5, 3, 2])
x = tf.constant([3,
                 1,
                 5])
b = tf.constant([[2]])   # make bias 2D as well
w = tf.reshape(w, (1, 3))
x = tf.reshape(x, (3, 1))
y = tf.matmul(w, x) + b
#without matmal what you can do is simply doo by MATRICES method!!!!
print(y)

tf.Tensor([[30]], shape=(1, 1), dtype=int32)


In [ ]:
a = tf.constant([54, 37, 2],dtype =tf.float32)  #yeh kyun karte hai cause saare no are in float during doing neural network!!!!
print(a)

tf.Tensor([54. 37.  2.], shape=(3,), dtype=float32)


#BUILT - IN FUNCTIONS!!

In [ ]:
a = tf.constant([5, 3, 2])
b = w = tf.constant([4,7,8])
add=tf.add(a,b)
print(add)  #BUILT-IN FUNCTION!!!

tf.Tensor([ 9 10 10], shape=(3,), dtype=int32)


#Reduce_Mean and Reduce_Sum!!

In [ ]:
#a=[1,2,3]
#reduction function to calculate loss function error find
#tf.reduce_sum of a!!!!!
a = tf.constant([5, 3, 2])
print(tf.reduce_sum(a))
# and now to find out the mean!!!
print(tf.reduce_mean(a))   #tensor ke elements ko add karna!!!!#during list and numpy we have done it!!!

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


##Numpy is CPU friendly and deep learning things are GPU ke dost!!!

In [ ]:
import tensorflow as tf
a = tf.constant([0.33,0.66,0.34])
print(tf.random.uniform([3]))  #Generates randomly within this range!!!!

tf.Tensor([0.60458374 0.7468035  0.35423875], shape=(3,), dtype=float32)


#HERE are the functions like tf.reduce_mean,tf.reduce_max,tf.reduce_min!!!

In [ ]:
import tensorflow as tf
a = tf.constant([0.33,0.66,0.34])
print(tf.random.uniform([30],minval = 5 , maxval = 12))
print("------------------------------------------------")
print(f"The mean is: {tf.reduce_mean(a)}")
print("--------------------------------------------")
print(f"The maximum is: {tf.reduce_max(a)}")
print("--------------------------------------------")
print(f"The minimum is: {tf.reduce_min(a)}")

tf.Tensor(
[ 8.272624  11.38378   11.873782   6.0294986  9.904357   5.375808
  7.5987835  8.666283   7.613076   7.8318706  8.680804   9.422508
  9.240149   8.406829   5.1000357  8.900734   9.697845   7.3146234
 11.744516  10.825371   8.778399   8.417988   7.5085344  9.870213
  5.7022524  8.978846   8.676318   6.4505196  9.931001   5.3971076], shape=(30,), dtype=float32)
------------------------------------------------
The mean is: 0.44333335757255554
--------------------------------------------
The maximum is: 0.6600000262260437
--------------------------------------------
The minimum is: 0.33000001311302185


#TYPE - CASTING!!!
Conversion of int to float!!

In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
b = tf.cast(a, tf.float32)   #Float 16 onwards and more like float32 , float64 in tensorflow but pytorch supports more too could
#also be taken depends on the accuracy)!!
print(b)

tf.Tensor([1244.   45.   14.], shape=(3,), dtype=float32)


In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
b = tf.cast(a, tf.float16)   #Float 16 onwards and more like float32 , float64 in tensorflow but pytorch supports more too could
#also be taken depends on the accuracy)!!
print(b)

tf.Tensor([1244.   45.   14.], shape=(3,), dtype=float16)


In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
b = tf.cast(a, tf.float64)   #Float 16 onwards and more like float32 , float64 in tensorflow but pytorch supports more too could
#also be taken depends on the accuracy)!!
print(b)

tf.Tensor([1244.   45.   14.], shape=(3,), dtype=float64)


#To check for greator,equal, or greater_equal,less_equal or smaller!!

In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
x= tf.greater(a,3)  #Here this means in a we are saying a is greater to 3!!
print(x)

tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
x= tf.equal(a,3)  #Here this means in a we are saying a is equal to 3!!
print(x)

tf.Tensor([False False False], shape=(3,), dtype=bool)


In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
x= tf.less(a,3)  #Here this means in a we are saying a is less to 3!!
print(x)

tf.Tensor([False False False], shape=(3,), dtype=bool)


In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
x= tf.greater_equal(a,3)
print(x)

tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
x= tf.less_equal(a,3)  #Here this means in a we are saying a is less to 3!!
print(x)

tf.Tensor([False False False], shape=(3,), dtype=bool)


In [ ]:
#QUESTION:-
#MATRICES:-
#Here we will take two matrix:-
A = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
B = [[9, 8, 7],[6, 5, 4],[3, 2, 1]]
#Taken variable result so that we will get good example for this question:-
r =[[0, 0, 0],[0, 0, 0],[0, 0, 0]]
for i in range(3): #it means the rows of  A matrix
    for j in range(3):#it means coloumns of B matrix
        for k in range(3):#the shape that it will check everything
            r[i][j]+=A[i][k]*B[k][j]
print("Result of this:")
for i in r:
    print(i)

Result of this:
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


In [ ]:
#2 by 3 and 3 by 2 !!!!!

In [ ]:
A = [[1, 2, 3],
     [4, 5, 6]]

B = [[7, 8],
     [9, 10],
     [11, 12]]

r = [[0, 0],
     [0, 0]]

for i in range(2):
    for j in range(2):
        for k in range(3):
            r[i][j] += A[i][k] * B[k][j]

print("Result of this:")
for i in r:
    print(i)

Result of this:
[58, 64]
[139, 154]


In [ ]:
#First we will take the input of MATRIX A:-
r_A = int(input("Enter rows of A: "))
c_A = int(input("Enter columns of A: "))
A = []
print("Enter elements of Matrix A:")
for i in range(r_A):
    row = []
    for j in range(c_A):
        v = int(input(f"Enter element A[{i}][{j}]: "))
        row.append(v)
    A.append(row)

#Second we will take the input of MATRIX B:-
r_B = int(input("Enter rows of B: "))
c_B = int(input("Enter columns of B: "))
B = []
print("Enter elements of Matrix B:")
for i in range(r_B):
    row = []
    for j in range(c_B):
        v = int(input(f"Enter element B[{i}][{j}]: "))
        row.append(v)
    B.append(row)

#Let us check if multiplication is possible or not!!!
if c_A != r_B:
    print("Hence, Multiplication not possible!!!")
else:
    r = []
    for i in range(r_A):     #or here we can do list comprehension like!!
    #r = [[0 for j in range(c_B)] for i in range(r_A)]
        r.append([0] * c_B)

    for i in range(r_A):
        for j in range(c_B):
            for k in range(c_A):
                r[i][j] += A[i][k] * B[k][j]
    print("So now ; Result of multiplication:")
    for i in r:
        print(i)

Enter rows of A: 2
Enter columns of A: 2
Enter elements of Matrix A:
Enter element A[0][0]: 2
Enter element A[0][1]: 2
Enter element A[1][0]: 2
Enter element A[1][1]: 2
Enter rows of B: 2
Enter columns of B: 3
Enter elements of Matrix B:
Enter element B[0][0]: 4
Enter element B[0][1]: 4
Enter element B[0][2]: 4
Enter element B[1][0]: 4
Enter element B[1][1]: 4
Enter element B[1][2]: 4
So now ; Result of multiplication:
[16, 16, 16]
[16, 16, 16]


In [ ]:
#BIAS :-To maintian the correctness in the middle ...

In [ ]:
import tensorflow as tf
w = tf.constant([[5,4,3],
                 [2,2,3],
                 [1,2,6],
                 [2,1,2]])
x = tf.constant([[3],
                 [2],
                 [1]])
b = tf.constant([[1],
                 [5],
                 [6],
                 [0]])

y = tf.matmul(w, x) + b

print(y)

tf.Tensor(
[[27]
 [18]
 [19]
 [10]], shape=(4, 1), dtype=int32)


#DOING SAME USING NUMPY:-

In [ ]:
import numpy as np
#here w is the weight
w = np.array([[1,2,3,4,5,6,7],  #neuron 1
              [1,2,3,4,5,6,7],  #neuron 2
              [1,2,3,4,5,6,7],  #neuron 3
              [1,2,3,4,5,6,7],  #neuron 4
              [1,2,3,4,5,6,7],  #neuron 5
              [1,2,3,4,5,6,7],  #neuron 6
              [1,2,3,4,5,6,7],  #neuron 7
              [1,2,3,4,5,6,7]   #neuron 8  # 7 weight each
              ])        #multiple neurons here....
#here x is the input
x = np.array([1,2,3,4,5,6,7])   # one data point with 7 characteristic....

#here b is bias...
b = ([0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8])  #one bias each for 8 neurons...

# dot product
y = np.dot(w,x) + b

print(y)


[140.1 140.2 140.3 140.4 140.5 140.6 140.7 140.8]


In [ ]:
#So you always have:

'''Weights (W) → what the model learns
Bias (b) → adjustment
Activation function → adds intelligence/non-linearity
 Full pipeline (real picture)
Input → Linear (W·x + b) → Activation → Next Layer → Output → Loss → Backpropagation
 Components in deep learning
 1. Linear operations
Matrix multiplication (Wx)
Core computation
2. Activation functions
ReLU, Sigmoid, Tanh, GELU
Add non-linearity
3. Loss function
Measures error
Example: MSE, Cross-Entropy
4. Optimizer
Updates weights
Example: Gradient Descent, Adam
5. Backpropagation
Computes gradients
Helps model learn'''

'Weights (W) → what the model learns\nBias (b) → adjustment\nActivation function → adds intelligence/non-linearity\n Full pipeline (real picture)\nInput → Linear (W·x + b) → Activation → Next Layer → Output → Loss → Backpropagation\n Components in deep learning\n 1. Linear operations\nMatrix multiplication (Wx)\nCore computation\n2. Activation functions\nReLU, Sigmoid, Tanh, GELU\nAdd non-linearity\n3. Loss function\nMeasures error\nExample: MSE, Cross-Entropy\n4. Optimizer\nUpdates weights\nExample: Gradient Descent, Adam\n5. Backpropagation\nComputes gradients\nHelps model learn'

In [ ]:
#ACTIVATION FUNCTION:- LINEAR CONCEPT IN MACHINE LEARNING BUT IN DEEP LEARNING WHAT THERE IS LINEAR LINE GRAPH AND LIKE USING INSIDE WIEGHT SOO NOW
#TAKI complex data ek baar mai no process and so many hidden layers and not happened nut...
#linear sidha de do toh dl soo what we do is non lineaty functions activation funciton gives for non linear functions ...
#ACTIVATION FUNCITON :RELU,SIGMOID,SOFTMAX TANH,GELU...
#RELU:-LINEAR TO NON LINEAR(negative values ko remove karke 0 and then positive remains same.....isse non linearty property add ho jaata hai and became fast )
#ek esa data pe kaam karta hai jahan negatove values nahi dekhi jaati like in photos and all the pixels and all like the fetaures and age we focus  on this...
#negative values should be ignored for fast calculations soo error should be less soo what we do is use RELU there..Like brain have neurons sab neuarons ka apna role hai.....
#sab neurons at a time nahi use nahi hona chaiye onyl and only......USELESS NEURONS SHOULD BE REMOVED AND WILL NOT DO GOOD WORK..
#So,IN CV no negative so using RELU but if we need to see negative......then we use TANH!!!
#relu range is 0 to infinty...
#TANH KA range -infinty se infinty tak like to work on text data or time series data jaise stock market...
#SIGMOID yeh output layer mai kaam karenge..when output layer come if hidden layer se nikla 0.7 (0-1) toh yeh 1/1+exponential..not used in hidden layer kyunki
#matlab calculations mushkil toh tab time lagega bohot sooo sigmoid should be avoided soo used in output layer!!!
#binary classification main ya toh hoga ya fhir nahi hoga (0-1) same function...
#jahan multiple scenarios asking konsa animal hai maybe dog,cat,cow sooo vahan sigmoidn failed then comes to play softmax....
#GELU is like Relu but is smart and intelligent relu cancels directly negative values it uses negative values intelligently....
#postive values kum ho gaye in images then use TAN not RELU!

#RELU!!

In [ ]:
import numpy as np
X= [0.5,2,-4,-9,-1,0]
def relu(x):
  return np.maximum(0,x)  #if there is an array negative ko 0 and will compare the values whatever is max will be there!!
relu(x)


array([1, 2, 3, 4, 5, 6, 7])

#SIGMOID FUNCTION!!

In [ ]:
import numpy as np
X = np.array([0.5, 2, -4, -9, -1, 0])
def sigmoid(x):
    return 1 / (1 + np.exp(-x))  #or we can use the map library also!!

print(sigmoid(X))

[6.22459331e-01 8.80797078e-01 1.79862100e-02 1.23394576e-04
 2.68941421e-01 5.00000000e-01]


In [ ]:
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error

X = np.array([0.5, 2, -4, -9, -1, 0])

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

y_pred = sigmoid(X)
print(y_pred)




[6.22459331e-01 8.80797078e-01 1.79862100e-02 1.23394576e-04
 2.68941421e-01 5.00000000e-01]


In [ ]:
#Input → Linear (W·x + b) → Activation → Next Layer → Output → Loss → Backpropagation

In [ ]:
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
X = np.array([0.5, 2, -4, -9, -1, 0])
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
y_pred = sigmoid(X)
y_true = np.array([1, 1, 0, 0, 0, 1])
mse = mean_squared_error(y_true, y_pred)

# Output
print("Sigmoid Output:", y_pred)
print("MSE:", mse)

Sigmoid Output: [6.22459331e-01 8.80797078e-01 1.79862100e-02 1.23394576e-04
 2.68941421e-01 5.00000000e-01]
MSE: 0.0798998833864495


In [ ]:
#softmax in every value but har ek mai apply karke and alag alag category like(0-5),(8-3)!
#tan  -infinty se infinity like i - cosx!!!yeh bhi e*x - e*x/e*n +e*n!!!

In [ ]:
#FORWARD PROPAGATION AND BACKWARD PROPAGATION:-
#0 - SE - X KE BICH IN RELU THE COMPUATION IS FORWARD PROPAGATION!!!!

In [ ]:
#MAAN LO : -2.5 LIKE ERROR KO EVALUATE KARKE BAIS KO KARKE GRADIENT:-LOSS KO KITNA LOSS HAI IN DIRECTION LIKE MSE MAI NO DIRECTION ONLY DISTANCE IN INPUT AND OUPUT SIMILARY LIKE IT but has some kind of direction...
#putput calculate karne ke baad weight ko evaluate karte hai toh forward propagation!!!!!!!1

In [ ]:
#GRADIENT DECENT :-If model and predicting soo agar predict kara toh kitna galat kara kis direction mai!!!!!

In [ ]:
#CANCEL OUT POSITIVE NEGATIVE AND THEN THE OUTCOME!!!
#LEARN =(0.1-0.5)!!
#1 SE KAAFI ZYAADAAA EFFECT TOH UNDERFITTING AND OVERFITTING CONCEPTS COMES TO PLAY!!
#Y=WX+B!!
#Y=2*W+1!!
#LEARNING RATE = 0.01
#WEIGHT =0.5
#KITNA DURI PR KIDHAR HAI!!GRADIENT!!

In [ ]:
w= 0.5
lr=0.01
for i in range(5):
  y = 2 *(w-1)
print(y)

-1.0


In [ ]:
w= -0.5
lr=0.1 #learning weight!!
for i in range(80):
  gd = 2*(w-1)
  w=w-gd*lr
print(w)

0.999999973497294


In [ ]:
#yeh karne se wieght badhega and all of that!!!
#Target lekar chalyta hai and learning weight rakhne ke liye how many steps to be taken!!!

In [ ]:
#gradient giving directions!!

In [ ]:
current_weight = 0.5
lr=0.9

for i in range(150000):  #all data utne time utne chunks par participate karenge,time zyadaaa.price zyadaaa...data ko karne ki jagah optimise its steps....
  gd =(current_weight - (-0.17))  #jitna difference h utna on giving values chalega!!
  current_weight = current_weight - gd*lr

print(current_weight)

-0.17


In [ ]:
#3.5 to 17.5!!!
curr_we=3.5
lr=0.27


for i in range(10):
  gd= 2* (curr_we - 17.5) #direction
  curr_we = curr_we - gd * lr


print(curr_we)

17.49406109535241


In [ ]:
#TEXT/VARIABLE DATAS AND INTUTION OF CALCULUS AND VECTOR DB!!

In [1]:
#IT HELPS IN MINIMISING THE PREDICTION ERROR!!!