<a href="https://colab.research.google.com/github/Saisneha0209/Machine-Learning/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install tensorflow

#TENSORFLOW!!

In [ ]:
import tensorflow as tf
a=tf.constant(5)  #0 Dimension!!   #yahan constant matlab numpy mai array!!and in that np.array but here tf.constant!!
print(a)
b=tf.constant([45,56])
print(b)  #1 Dimension!!
c=tf.constant([[4,5,1],[4,6,7]])  #2 Dimension
print(c)
#On 4-D IT IS TENSOR!!!
#SAME VECTOR KO ADD,MULTIPLY KARNA!!!!

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([45 56], shape=(2,), dtype=int32)
tf.Tensor(
[[4 5 1]
 [4 6 7]], shape=(2, 3), dtype=int32)


#ALL ARITHMETIC OPERATIONS!!

In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a+b)

tf.Tensor([50], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a*b)

tf.Tensor([225], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a/b)

tf.Tensor([0.11111111], shape=(1,), dtype=float64)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a//b)

tf.Tensor([0], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5])
b=tf.constant([45])
print(a-b)

tf.Tensor([-40], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([5,6,7])
b=tf.constant([1,2,3,4])
#print(a+b) THIS WILL GIVE ERROR BECAUSE YOU HAVE LEARNT IN MATRICES THAT ROW * COLOUMNS MUST BE EQUAL TO MEANS THE
#COLOUMNS SHOULD BE EQUAL TO ROW OF SECOND MATRICES .....

#Y = W * X + B

In [ ]:
import tensorflow as tf
w = tf.constant([[5,4,3],
                 [2,2,3],
                 [1,2,6],
                 [2,1,2]])
x = tf.constant([[3],
                 [2],
                 [1]])
b = tf.constant([[1],
                 [5],
                 [6],
                 [0]])

y = tf.matmul(w, x) + b

print(y)
#broadcasting laws in this and do it like 3-D!!!!!

tf.Tensor(
[[27]
 [18]
 [19]
 [10]], shape=(4, 1), dtype=int32)


In [ ]:
#zero tf and once tf!!!!   (matrices)

In [ ]:
import tensorflow as tf

w = tf.constant([5, 3, 2])
x = tf.constant([3,
                 1,
                 5])
b = tf.constant([[2]])   # make bias 2D as well
w = tf.reshape(w, (1, 3))
x = tf.reshape(x, (3, 1))
y = tf.matmul(w, x) + b
#without matmal what you can do is simply doo by MATRICES method!!!!
print(y)

tf.Tensor([[30]], shape=(1, 1), dtype=int32)


In [ ]:
a = tf.constant([54, 37, 2],dtype =tf.float32)  #yeh kyun karte hai cause saare no are in float during doing neural network!!!!
print(a)

tf.Tensor([54. 37.  2.], shape=(3,), dtype=float32)


#BUILT - IN FUNCTIONS!!

In [ ]:
a = tf.constant([5, 3, 2])
b = w = tf.constant([4,7,8])
add=tf.add(a,b)
print(add)  #BUILT-IN FUNCTION!!!

tf.Tensor([ 9 10 10], shape=(3,), dtype=int32)


#Reduce_Mean and Reduce_Sum!!

In [ ]:
#a=[1,2,3]
#reduction function to calculate loss function error find
#tf.reduce_sum of a!!!!!
a = tf.constant([5, 3, 2])
print(tf.reduce_sum(a))
# and now to find out the mean!!!
print(tf.reduce_mean(a))   #tensor ke elements ko add karna!!!!#during list and numpy we have done it!!!

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


##Numpy is CPU friendly and deep learning things are GPU ke dost!!!

In [ ]:
import tensorflow as tf
a = tf.constant([0.33,0.66,0.34])
print(tf.random.uniform([3]))  #Generates randomly within this range!!!!

tf.Tensor([0.60458374 0.7468035  0.35423875], shape=(3,), dtype=float32)


#HERE are the functions like tf.reduce_mean,tf.reduce_max,tf.reduce_min!!!

In [ ]:
import tensorflow as tf
a = tf.constant([0.33,0.66,0.34])
print(tf.random.uniform([30],minval = 5 , maxval = 12))
print("------------------------------------------------")
print(f"The mean is: {tf.reduce_mean(a)}")
print("--------------------------------------------")
print(f"The maximum is: {tf.reduce_max(a)}")
print("--------------------------------------------")
print(f"The minimum is: {tf.reduce_min(a)}")

tf.Tensor(
[ 8.272624  11.38378   11.873782   6.0294986  9.904357   5.375808
  7.5987835  8.666283   7.613076   7.8318706  8.680804   9.422508
  9.240149   8.406829   5.1000357  8.900734   9.697845   7.3146234
 11.744516  10.825371   8.778399   8.417988   7.5085344  9.870213
  5.7022524  8.978846   8.676318   6.4505196  9.931001   5.3971076], shape=(30,), dtype=float32)
------------------------------------------------
The mean is: 0.44333335757255554
--------------------------------------------
The maximum is: 0.6600000262260437
--------------------------------------------
The minimum is: 0.33000001311302185


#TYPE - CASTING!!!
Conversion of int to float!!

In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
b = tf.cast(a, tf.float32)   #Float 16 onwards and more like float32 , float64 in tensorflow but pytorch supports more too could
#also be taken depends on the accuracy)!!
print(b)

tf.Tensor([1244.   45.   14.], shape=(3,), dtype=float32)


In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
b = tf.cast(a, tf.float16)   #Float 16 onwards and more like float32 , float64 in tensorflow but pytorch supports more too could
#also be taken depends on the accuracy)!!
print(b)

tf.Tensor([1244.   45.   14.], shape=(3,), dtype=float16)


In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
b = tf.cast(a, tf.float64)   #Float 16 onwards and more like float32 , float64 in tensorflow but pytorch supports more too could
#also be taken depends on the accuracy)!!
print(b)

tf.Tensor([1244.   45.   14.], shape=(3,), dtype=float64)


#To check for greator,equal, or greater_equal,less_equal or smaller!!

In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
x= tf.greater(a,3)  #Here this means in a we are saying a is greater to 3!!
print(x)

tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
x= tf.equal(a,3)  #Here this means in a we are saying a is equal to 3!!
print(x)

tf.Tensor([False False False], shape=(3,), dtype=bool)


In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
x= tf.less(a,3)  #Here this means in a we are saying a is less to 3!!
print(x)

tf.Tensor([False False False], shape=(3,), dtype=bool)


In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
x= tf.greater_equal(a,3)
print(x)

tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [ ]:
import tensorflow as tf
a = tf.constant([1244,45,14])
x= tf.less_equal(a,3)  #Here this means in a we are saying a is less to 3!!
print(x)

tf.Tensor([False False False], shape=(3,), dtype=bool)


In [4]:
#QUESTION:-
#MATRICES:-
#Here we will take two matrix:-
A = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
B = [[9, 8, 7],[6, 5, 4],[3, 2, 1]]
#Taken variable result so that we will get good example for this question:-
r =[[0, 0, 0],[0, 0, 0],[0, 0, 0]]
for i in range(3): #it means the rows of  A matrix
    for j in range(3):#it means coloumns of B matrix
        for k in range(3):#the shape that it will check everything
            r[i][j]+=A[i][k]*B[k][j]
print("Result of this:")
for i in r:
    print(i)

Result of this:
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]
